### ISSUE TITLE
GET Endpoint to get a User's Availabilities

### ISSUE THREAD

**Issue by AimeeShao** [HKN-UCSD/hkn-server#133]
Create a POST endpoint that returns a user's availabilities in the format shown below:

Body:
- User_id (FK to app_user) (PK)
- Induction class (FK to induction class) (PK)

Return: Availabilities (jsonb) 
E.g. 
```
{
	“x date”: [
		{“start”: ISO, “end”: ISO}
	]
}
```

**Comment by godwinpang** [comment]
GET /users/{user_Id}/availabilities?induction_class={induction_class}

**Comment by AimeeShao** [comment]
Why do we need the query of induction class?
I'm thinking we only need induction_class query if a user can have multiple induction classes.
If it is to limit their availability times, shouldnt it only display availabilities for a user's induction class when they user fills out their availability?
