### ISSUE TITLE
Create error snackbar for frontend errors instead of console.log

### ISSUE THREAD

**Issue by godwinpang** [HKN-UCSD/hkn-server#181]
https://material-ui.com/components/snackbars/

**Comment by thaigillespie** [comment]
@yuw006 you want to do this?

**Comment by yuw006** [comment]
> @yuw006 you want to do this? If you do I'll assign it to you. Also, feel free to pick anything else you want to do in the list of issues. If you do, let me know and I'll provide more info about it : )

Sounds good
