### ISSUE TITLE
Increase default number of rows for tables

### ISSUE THREAD

**Issue by godwinpang** [HKN-UCSD/hkn-server#192]
higher default number of rows for tables (to 20 entries per table page

**Comment by thaigillespie** [comment]
@godwinpang is this issue for frontend or backend?

**Comment by thaigillespie** [comment]
@audreygao you want to take on this? Should be an easy issue to get yourself familiarized with the codebase

**Comment by audreygao** [comment]
@thaigillespie Yea Sure I'll take on this issue.
