### ISSUE TITLE
Add "static" information about an event on its corresponding guest event signin page

### ISSUE THREAD

**Issue by thaigillespie** [HKN-UCSD/hkn-server#225]
Currently the event sign in page for guests only have the sign in form and nothing else. Since we're switching to in person starting this upcoming Fall 2021 quarter, we should also display event information on that guest event signin page as well so attendees know exactly the details of the event when they sign in (either by themselves or at the event itself via chromebooks at the table).

Information to add includes (but not limited to): event host, date+time, our contacts, etc., i.e. stuff that we already store on our db for an event or stuff that we can just hardcode (like contact info)

**Comment by thaigillespie** [comment]
@Divneet18 you want to take on this?

**Comment by Divneet18** [comment]
yes sure!
