### ISSUE TITLE
Handle guest event sign in that uses existing email by prompting them to sign in as an HKN affiliate

### ISSUE THREAD

**Issue by thaigillespie** [HKN-UCSD/hkn-server#238]
Let the user know that if the email they used to sign in to an event as a guest is already associated with an account, then they will have to sign in using their account instead. Can do this via a popup/modal, then have two buttons on that popup/modal, one to redirect them back to the Inductee/Guest Page and the other to redirect them straight to the login page itself. Or you can just have one button on the popup/modal that when clicked on will lead the user to our login page. Refer to the HKN Software Development Planning doc for more details (PM me @thaigillespie for the link to the doc if you don't have it already). 

Should mostly be frontend. May contain a bit of backend work if the logic for short-circuiting on existing email doesn't already exist on the respective endpoint in the backend (the endpoint for guest event sign in).

**Comment by thaigillespie** [comment]
Updated the issue description to reflect the changes on the planning doc

**Comment by yuw006** [comment]
closed by pull request #261
