### ISSUE TITLE
Setup CircleCI job for running build

### ISSUE THREAD

**Issue by godwinpang** [HKN-UCSD/hkn-server#24]
Make sure that the project builds `npm run build`

.... which incidentally also runs lint so maybe we can take that outta package.json idk just run the build to make sure the code compiles

**Comment by thaigillespie** [comment]
So you want to just run npm run lint and npm run build or just npm run build? Seems like no pref there so I'll run both

**Comment by godwinpang** [comment]
run prettier too while you're at it

**Comment by thaigillespie** [comment]
'npx prettier' right? Should I run that on all files? So something like 'npx prettier ./*'?

**Comment by godwinpang** [comment]
yeah i think `npx prettier "src/**/.ts"` probably better

**Comment by thaigillespie** [comment]
I'm thinking of running 'npm run build' then 'npx prettier ./*' or smth like that

**Comment by godwinpang** [comment]
*.ts

**Comment by godwinpang** [comment]
wait running prettier just prettifies the code in the ci job lol

**Comment by thaigillespie** [comment]
lol so it doesn't apply to the pushed code huh

**Comment by godwinpang** [comment]
run sth like `prettier --check "src/**/*.ts"`

**Comment by thaigillespie** [comment]
--check doesn't format the listed files I think, we just want to inform devs of files that are not formatted then?

**Comment by godwinpang** [comment]
yeah exactly that's the point - idt we can fix code that's malformatted but we can gate it
If you have control over the git host then you can run prettier per push but we dont so just gating it is good enough

**Comment by thaigillespie** [comment]
Gate?

**Comment by godwinpang** [comment]
as in throw up a red cross so we know to throw them into the social distancing prison
