### ISSUE TITLE
Add endpoint and corresponding UI in FE that lets officers edit attendances (if they need to)

### ISSUE THREAD

**Issue by thaigillespie** [HKN-UCSD/hkn-server#243]
Add an endpoint in the backend, preferably in a file called AttendanceController (unless it already exists by the time you work on this issue, you'll have to make this yourself since this is not in the codebase as of now, but there are plenty of examples so dw), that lets an officer edit an Attendance entity by ID (i.e. find the needed Attendance entity by its ID then edit some information that it holds). 

Then, run autogen on the frontend in order to have the updated API that is changed due to our adding this new endpoint. Then, using the autogenerated API calls, create a component, like a button or something like that, and stick it onto the attendance entries in the AttendanceTable and CheckOffTable in EventDetailsPage. This button should either redirect to a new page that allows an officer to make changes to the information on the attendance entry or allow editing right on the attendance entry in the AttendanceTable or CheckOffTable.

**Comment by godwinpang** [comment]
> Then, run autogen on the frontend

could we have this step documented? I think this would have to be a step that should be done on every backend pr change

**Comment by thaigillespie** [comment]
> 
> 
> > Then, run autogen on the frontend
> 
> could we have this step documented? I think this would have to be a step that should be done on every backend pr change

Yeah that's a good point I can document that
