### ISSUE TITLE
Add edit page for description field of account sign up form

### ISSUE THREAD

**Issue by thai-tgil** [HKN-UCSD/hkn-server#257]
Since description field is just displaying a text on certain information that we would like people signing up for an account to know, we might need to change it from time to time depending on what we want people to see. This means we need an edit form to modify what the description field contains (you can use Formik if you want, or find some other solution to this). Since there is no good place to store the contents of the description field in the backend with how we do things, it's best to store contents of description field into a React context, named `SignUpFormContext` or something like that. This edit page which contains an edit form allows **officers** to modify the content of that description field using the context.

For the person working on this task, work with people working on issue #255 to see whoever is responsible for creating the context and put that in a separate, standalone commit for the person working on the other issue to cherry pick that commit to their branch.

A friendly reminder that only `officers` have access to this edit page and no one else.

**Comment by thaigillespie** [comment]
Okay nevermind @kyle1373 @audreygao oversight on my part React Context should not be used for persistent data (and description's content is persistent data) so React Context probably won't work for description field here. Will probably have to use database or cookies (pref. db) I'll need some time to think about this if yall don't mind. For now just ignore the description field

**Comment by thai-truong** [comment]
Closed bc scope changed so now description field is static
