### ISSUE TITLE
Error Handler

### ISSUE THREAD

**Issue by godwinpang** [HKN-UCSD/hkn-server#27]
Write short custom error handler to return errors as json

**Comment by thaigillespie** [comment]
I just wanted to ask what this error handler is supposed to be? Is is a middleware? A service? Also, what is it supposed to do? Just take in some parameters and return errors as json? I think it would be great to have a bit more specificity on this, since I'm not sure what to do with it just yet.

**Comment by godwinpang** [comment]
https://expressjs.com/en/guide/error-handling.html

this returns HTML, we want JSON
