### ISSUE TITLE
Deployment Pipeline Enhancements

### ISSUE THREAD

**Issue by godwinpang** [HKN-UCSD/hkn-server#58]
Now that we have auth on endpoints, we can work on having an actual prod api! :)

master is golden => deploy to `api.hknucsd.com`
we should have a dev branch that deploys to `dev.hknucsd.com`

that way we can have feature branches that branch off dev and stuff (and maybe have some naming consistency)

we'll need to setup a new heroku app for prod and add the appropriate subdomain for that on namecheap

whoever takes this on pm @godwinpang and we can setup some time to make docs

**Comment by thaigillespie** [comment]
Both apps are deployed. The one linked to master branch is at [](http://api.hknucsd.com/ ) (this is prod) and the one linked to dev branch is at [](http://dev.api.hknucsd.com/) (this is dev)

**Comment by godwinpang** [comment]
awesome work @thaigillespie

**Comment by thaigillespie** [comment]
Ty : ) I synced up the db for prod, but it doesn't have any data yet as of now. Also, I think I need to write docs for this so where should I write docs? Root-level readme right?

**Comment by godwinpang** [comment]
I honestly don’t know where docs should live for now - as long as it’s somewhere for now then I think it’s ok

**Comment by thaigillespie** [comment]
I think this can be closed @godwinpang ?
