### ISSUE TITLE
Startup postgres in a single docker container locally

### ISSUE THREAD

**Issue by godwinpang** [HKN-UCSD/hkn-server#70]
tl;dr I want to run `npm run db:start` and `npm run db:stop` to stand up and kill the postgres docker container.
Empty db is *fine*.

you shouldn't need to write a docker file since I *think* we can directly use the base postgres image. Please remember to use the same pg version as we are using on heroku

Non-goal: seeding database

This should be straightforward - tons of guides online

https://docs.docker.com/engine/reference/run/

**Comment by thaigillespie** [comment]
What's our POSTGRES_PASSWORD btw? When I run the command below

`docker run -it --name postgres_container -p <port>:<port> postgres:12.3`

It gives an error and asks me for POSTGRES_PASSWORD

**Comment by thaigillespie** [comment]
Also not really sure if we should run this detached or in foreground https://docs.docker.com/engine/reference/run/#detached-vs-foreground

**Comment by godwinpang** [comment]
foreground is fine - just put anything for postgres_password i think

**Comment by godwinpang** [comment]
u can specify env vars with -e

**Comment by thaigillespie** [comment]
sounds good tysm

**Comment by thaigillespie** [comment]
Still gives me an error even though I specified an env var, it still creates a container tho.
```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.

       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

Command: `docker run -it --name postgres_container -p 8080:8080 postgres:12.3 -e POSTGRES_PASSWORD=asfsd`

**Comment by godwinpang** [comment]
Oh put it before you specify the base image maybe

**Comment by godwinpang** [comment]
to clarify - for tests you'll want to run it detached; you should also forward 5432 instead of 8080

**Comment by godwinpang** [comment]
Command: `docker run -it --name postgres_container -p 5432:5432 -e POSTGRES_PASSWORD=asfsd -d postgres:12.3`
