### ISSUE TITLE
Mislabelled return type for saveAppUser

### ISSUE THREAD

**Issue by godwinpang** [HKN-UCSD/hkn-server#82]
We probably want to return a promise here, so no need to await. If you're returning after awaiting then you've resolved the promise already :)

https://github.com/HKN-UCSD/hkn-server/blob/26ccd81fc57dfb8a4ba7f5739dc3de5c8c4adc24/src/services/AppUserService.ts#L12

**Comment by thaigillespie** [comment]
Fixed (also fixed saveNonAffiliates bc it calls saveAppUser with await in its return statement), will push it along with the other stuff I did for user endpoints.
