### ISSUE TITLE
Figure out why tsconfig.json keeps changing

### ISSUE THREAD

**Issue by godwinpang** [HKN-UCSD/hkn-server#98]

**Comment by thaigillespie** [comment]
I think this is just because a newline is added to the end of the file whenever it's in local, but that newline is removed whenever it's on github. Rn tsconfig.json for hkn-server for me has 35 lines, while the one on gh has 34 lines (dev branch)

**Comment by godwinpang** [comment]
Hm maybe it’s because I’m not on vs code lol

**Comment by thaigillespie** [comment]
maybe lol

**Comment by thaigillespie** [comment]
Should we close this then?

**Comment by thaigillespie** [comment]
whitespace difference between linux and windows is the reason here, so gonna close this now
